# $ custom_build_script

# CDN domains of domestic services that should use DIRECT both in China and abroad.
# Match this ruleset before domestic when routing other domestic traffic back to China.
# The build script also includes these rules in the legacy domestic output.


# >> Bilibili
# Bilibili CDN
DOMAIN-SUFFIX,hdslb.com

# >> NetEase
# NetEase Music CDN
DOMAIN-SUFFIX,music.126.net

# >> 360
DOMAIN-SUFFIX,qhimg.com
DOMAIN-SUFFIX,qhimgs.com
DOMAIN-WILDCARD,qhimgs?.com
DOMAIN-SUFFIX,qhres.com
DOMAIN-SUFFIX,qhres2.com
