import type { DNSMapping } from './direct';

export const DOMESTICS = {
  ALIBABA: {
    hosts: {
      'dns.alidns.com': ['223.5.5.5', '223.6.6.6', '2400:3200:baba::1', '2400:3200::1']
    },
    dns: 'quic://dns.alidns.com:853',
    domains: [
      'uc.cn',
      'ucweb.com',
      'alibaba.com',
      '+alicdn.com',
      '+ialicdn.com',
      '+myalicdn.com',
      '+alidns.com',
      '+aliimg.com',
      'aliyun.com',
      '+aliyuncs.com',
      '+alikunlun.com',
      '+alikunlun.net',
      '+cdngslb.com',
      'alipay.com',
      'alipay.cn',
      'alipay.com.cn',
      '+alipayobjects.com',
      'alibaba-inc.com',
      '+alibabausercontent.com',
      'alibabadns.com',
      'alicloudccp.com',
      'alipan.com',
      'aliyundrive.com',
      'aliyundrive.net',
      'cainiao.com',
      'cainiao.com.cn',
      'cainiaoyizhan.com',
      'guoguo-app.com',
      'etao.com',
      '1688.com',
      '16888.com',
      'amap.com',
      'gaode.com',
      'autonavi.com',
      'dingtalk.com',
      'mxhichina.com',
      'soku.com',
      'tb.cn',
      'taobao.com',
      '+taobaocdn.com',
      '+tbcache.com',
      'tmall.com',
      'tmall.hk',
      'xiami.com',
      'xiami.net',
      '+ykimg.com',
      'youku.com',
      'tudou.com',
      '+cibntv.net',
      'ele.me',
      '+elemecdn.com',
      'feizhu.com',
      'taopiaopiao.com',
      'fliggy.com',
      'koubei.com',
      'mybank.cn',
      'mmstat.com',
      'uczzd.cn',
      'iconfont.cn',
      'freshhema.com',
      'hemamax.com',
      'hemaos.com',
      'hemashare.cn',
      'shyhhema.com',
      'sm.cn',
      'npmmirror.com',
      'alios.cn',
      'wandoujia.com',
      '+aliapp.org',
      'tanx.com',
      'hellobike.com',
      '+hichina.com',
      '+yunos.com'
    ]
  },
  TENCENT: {
    hosts: {
      'dot.pub': ['120.53.53.53', '1.12.12.12', '1.12.34.56'],
      'doh.pub': ['120.53.53.53', '1.12.12.12', '1.12.34.56'],
      'dns.pub': ['120.53.53.53', '1.12.12.12', '1.12.34.56']
    },
    dns: 'https://doh.pub/dns-query',
    domains: [
      'dns.pub',
      'doh.pub',
      '+qcloud.com',
      '+gtimg.cn',
      '+gtimg.com',
      '+gtimg.com.cn',
      '+gdtimg.com',
      '+idqqimg.com',
      'igamecj.com',
      'myapp.com',
      '+myqcloud.com',
      'dnspod.com',
      '+qpic.cn',
      '+qlogo.cn',
      'qq.com',
      'qq.com.cn',
      'qq.wang',
      'qqmail.cn',
      'qqmail.com',
      'qzone.com',
      '+tencent-cloud.net',
      'tencent.com',
      'tencent.com.cn',
      'tencentmusic.com',
      'weixinbridge.com',
      'weixin.com',
      'wechat.com',
      'weiyun.com',
      'soso.com',
      'sogo.com',
      'sogou.com',
      '+sogoucdn.com',
      'roblox.cn',
      'robloxdev.cn',
      'wegame.com',
      'wegame.com.cn',
      'wegameplus.com',
      'cdn-go.cn',
      '+tencentcs.cn',
      '+qcloudimg.com',
      'dnspod.cn',
      'yitao.com',
      'anticheatexpert.com',
      '$url.cn',
      '+qlivecdn.com',
      '+tcdnlive.com',
      '+dnsv1.com'
    ]
  },
  BILIBILI_ALI: {
    dns: 'quic://dns.alidns.com:853',
    hosts: {},
    domains: [
      '$upos-sz-mirrorali.bilivideo.com',
      '$upos-sz-estgoss.bilivideo.com'
    ]
  },
  BILIBILI_BD: {
    dns: '180.76.76.76',
    hosts: {},
    domains: [
      '$upos-sz-mirrorbd.bilivideo.com',
      '$upos-sz-mirrorbos.bilivideo.com'
    ]
  },
  BILIBILI: {
    dns: 'https://doh.pub/dns-query',
    hosts: {},
    domains: [
      '$upos-sz-mirrorcoso1.bilivideo.com',
      '$acg.tv',
      '$b23.tv',
      'bilibili.cn',
      'bilibili.com',
      // 'bilibili.tv',
      '+acgvideo.com',
      '+bilivideo.com',
      '+bilivideo.cn',
      '+bilivideo.net',
      '+hdslb.com',
      '+biliimg.com',
      '+biliapi.com',
      '+biliapi.net',
      'biligame.cn',
      'biligame.com',
      'biligame.net',
      'bilicomic.com',
      'bilicomics.com',
      'bilibilipay.cn',
      'bilibilipay.com',
      '+bilicdn1.com'
    ]
  },
  XIAOMI: {
    dns: 'https://doh.pub/dns-query',
    hosts: {},
    domains: [
      'mi.com',
      'duokan.com',
      '+mi-img.com',
      'mi-fds.com',
      'mifile.cn',
      'miui.com',
      'xiaomi.com',
      'xiaomi.cn',
      'xiaomi.net',
      'xiaomiev.com',
      'xiaomiyoupin.com',
      // mi app store cdn
      'saxyit.com'
    ]
  },
  BYTEDANCE: {
    dns: '180.184.2.2',
    hosts: {},
    domains: [
      '+bytecdn.cn',
      '+toutiaoimg.com',
      '+toutiaoimg.cn',
      '+toutiaostatic.com',
      '+toutiaovod.com',
      '+toutiaocloud.com',
      'toutiaopage.com',
      'feiliao.com',
      'iesdouyin.com',
      '+pstatp.com',
      'snssdk.com',
      '+bytegoofy.com',
      'toutiao.com',
      'feishu.cn',
      'feishu.net',
      '+feishucdn.com',
      '+feishupkg.com',
      'douyin.com',
      '+douyinpic.com',
      '+douyinstatic.com',
      '+douyincdn.com',
      '+douyinliving.com',
      '+douyinvod.com',
      'huoshan.com',
      '+huoshanstatic.com',
      'huoshanzhibo.com',
      'ixigua.com',
      '+ixiguavideo.com',
      '+ixgvideo.com',
      '+volccdn.com',
      '+byted-static.com',
      'volces.com',
      'baike.com',
      '+zjcdn.com',
      '+zijieapi.com',
      'feelgood.cn',
      '+bytetcc.com', // Use hichina.com as NS
      '+bytednsdoc.com', // Uses alidns.com as NS
      '+byteimg.com' // Uses alidns.com as NS
    ]
  },
  BAIDU: {
    dns: '180.76.76.76',
    hosts: {},
    domains: [
      '91.com',
      'hao123.com',
      'baidu.cn',
      'baidu.com',
      'iqiyi.com',
      '+iqiyipic.com',
      '+baidubce.com',
      '+bcelive.com',
      '+baiducontent.com',
      '+baidustatic.com',
      '+bdstatic.com',
      '+bdimg.com',
      '+bcebos.com',
      '+baidupcs.com',
      '+baidubcr.com',
      '+yunjiasu-cdn.net',
      'tieba.com',
      'xiaodutv.com',
      'shifen.com',
      '+jomodns.com',
      '+bdydns.com',
      '+jomoxc.com',
      '+duapp.com',
      '+antpcdn.com' // Baidu PCDN
    ]
  },
  QIHOO360: {
    hosts: {
      'doh.360.cn': ['101.198.198.198', '101.198.199.200'],
      'dot.360.cn': ['101.198.198.198', '101.198.199.200'],
      'dns.360.cn': ['101.198.198.198', '101.198.199.200'],
      'doh.360.net': ['101.198.198.198', '101.198.199.200'],
      'dot.360.net': ['101.198.198.198', '101.198.199.200'],
      'dns.360.net': ['101.198.198.198', '101.198.199.200']
    },
    dns: 'https://dns.360.net/dns-query',
    domains: [
      '+qhimg.com',
      '+qhimgs0.com',
      '+qhimgs1.com',
      '+qhimgs2.com',
      '+qhimgs3.com',
      '+qhimgs4.com',
      '+qhimgs5.com',
      '+qhimgs6.com',
      '+qhres.com',
      '+qhres0.com',
      '+qhres1.com',
      '+qhres2.com',
      '+qhres3.com',
      '+qhres4.com',
      '+qhres5.com',
      '+qhres6.com',
      '+qhmsg.com',
      '+qhstatic.com',
      '+qhupdate.com',
      '+qihucdn.com',
      '360.com',
      '360.cn',
      '360.net',
      '360safe.com',
      '+360tpcdn.com',
      '360os.com',
      '+360webcache.com',
      '360kuai.com',
      'so.com',
      'haosou.com',
      'yunpan.cn',
      'yunpan.com',
      'yunpan.com.cn',
      '+qh-cdn.com',
      'baomitu.com'
    ]
  }
} satisfies Record<string, DNSMapping>;
