// @ts-check
export const DOMESTICS = {
  ALIBABA: {
    dns: 'quic://223.6.6.6:853',
    domains: [
      'uc.cn',
      'ucweb.com',
      'alibaba.com',
      'alicdn.com',
      'ialicdn.com',
      'alidns.com',
      'aliimg.com',
      'aliyun.com',
      'aliyuncs.com',
      'alikunlun.com',
      'alikunlun.net',
      'cdngslb.com',
      'alipay.com',
      'alipay.cn',
      'alipay.com.cn',
      'alipayobjects.com',
      'alibaba-inc.com',
      'alibabausercontent.com',
      'alicloudccp.com',
      'alipan.com',
      'aliyundrive.com',
      'aliyundrive.net',
      'cainiao.com',
      'cainiao.com.cn',
      'cainiaoyizhan.com',
      'guoguo-app.com',
      'etao.com',
      '1688.com',
      '16888.com',
      'amap.com',
      'gaode.com',
      'autonavi.com',
      'dingtalk.com',
      'dingtalk.com',
      'mxhichina.com',
      'soku.com',
      'tb.cn',
      'taobao.com',
      'taobaocdn.com',
      'tbcache.com',
      'tmall.com',
      'tmall.hk',
      'xiami.com',
      'xiami.net',
      'ykimg.com',
      'youku.com',
      'tudou.com',
      'cibntv.net',
      'ele.me',
      'elemecdn.com',
      'feizhu.com',
      'taopiaopiao.com',
      'fliggy.com',
      'koubei.com',
      'guoguo-app.com',
      'mybank.cn',
      'mmstat.com',
      'uczzd.cn',
      'iconfont.cn',
      'freshhema.com',
      'hemamax.com',
      'hemaos.com',
      'hemashare.cn',
      'shyhhema.com',
      'sm.cn',
      'npmmirror.com',
      'alios.cn',
      'wandoujia.com',
      'aliapp.org',
      'tanx.com',
      'hellobike.com'
    ]
  },
  TENCENT: {
    dns: 'https://120.53.53.53/dns-query',
    domains: [
      'dns.pub',
      'doh.pub',
      'qcloud.com',
      'gtimg.cn',
      'gtimg.com',
      'gtimg.com.cn',
      'gdtimg.com',
      'idqqimg.com',
      'igamecj.com',
      'myapp.com',
      'myqcloud.com',
      'dnspod.com',
      'qpic.cn',
      'qlogo.cn',
      'qq.com',
      'qq.com.cn',
      'qq.wang',
      'qqmail.cn',
      'qqmail.com',
      'qzone.com',
      'tencent-cloud.net',
      'tencent.com',
      'tencent.com.cn',
      'tencentmusic.com',
      'weixinbridge.com',
      'weixin.com',
      'wechat.com',
      'weiyun.com',
      'soso.com',
      'sogo.com',
      'sogou.com',
      'sogoucdn.com',
      'roblox.cn',
      'robloxdev.cn',
      'wegame.com',
      'wegame.com.cn',
      'wegameplus.com',
      'cdn-go.cn',
      'tencentcs.cn',
      'tencent-coud.cn',
      'qcloudimg.com',
      'dnspod.cn',
      'yunos.com',
      'yitao.com',
      'anticheatexpert.com',
      'url.cn',
      'qlivecdn.com',
      'tcdnlive.com',
      'dnsv1.com'
    ]
  },
  BILIBILI_ALI: {
    dns: 'quic://223.5.5.5:853',
    domains: [
      'upos-sz-mirrorali.bilivideo.com'
    ]
  },
  BILIBILI_BD: {
    dns: '180.76.76.76',
    domains: [
      'upos-sz-mirrorbos.bilivideo.com'
    ]
  },
  BILIBILI: {
    dns: 'https://120.53.53.53/dns-query',
    domains: [
      'upos-sz-mirrorcoso1.bilivideo.com',
      'acg.tv',
      'b23.tv',
      'acgvideo.com',
      'bilibili.cn',
      'bilibili.com',
      'bilibili.tv',
      'bilivideo.com',
      'bilivideo.cn',
      'bilivideo.net',
      'hdslb.com',
      'biliimg.com',
      'biliapi.com',
      'biliapi.net',
      'biligame.cn',
      'biligame.com',
      'biligame.net',
      'bilicomics.com',
      'bilibilipay.cn',
      'bilibilipay.com',
      'bilicdn1.com'
    ]
  },
  XIAOMI: {
    dns: 'https://120.53.53.53/dns-query',
    domains: [
      'mi.com',
      'duokan.com',
      'mi-img.com',
      'mifile.cn',
      'miui.com',
      'miwifi.com',
      'xiaomi.com',
      'xiaomi.cn',
      'xiaomi.net',
      'xiaomiyoupin.com',
      // mi app store cdn
      'saxyit.com'
    ]
  },
  BYTEDANCE: {
    dns: '180.184.2.2',
    domains: [
      'bytecdn.cn',
      'toutiaoimg.com',
      'toutiaoimg.cn',
      'toutiaostatic.com',
      'toutiaovod.com',
      'toutiaocloud.com',
      'toutiaopage.com',
      'feiliao.com',
      'iesdouyin.com',
      'pstatp.com',
      'snssdk.com',
      'toutiao.com',
      'feishu.cn',
      'feishu.net',
      'feishucdn.com',
      'feishupkg.com',
      'douyin.com',
      'douyinpic.com',
      'douyinstatic.com',
      'douyincdn.com',
      'douyinliving.com',
      'douyinvod.com',
      'huoshan.com',
      'huoshanstatic.com',
      'huoshanzhibo.com',
      'ixigua.com',
      'ixiguavideo.com',
      'ixgvideo.com',
      'volccdn.com',
      'byted-static.com',
      'volces.com',
      'baike.com'
    ]
  },
  BAIDU: {
    dns: '180.76.76.76',
    domains: [
      '91.com',
      'hao123.com',
      'baidu.cn',
      'baidu.com',
      'iqiyi.com',
      'iqiyipic.com',
      'baidubce.com',
      'bcelive.com',
      'baiducontent.com',
      'baidustatic.com',
      'bdstatic.com',
      'bdimg.com',
      'bcebos.com',
      'baidupcs.com',
      'baidubcr.com',
      'yunjiasu-cdn.net',
      'tieba.com',
      'xiaodutv.com',
      'shifen.com',
      'jomodns.com',
      'bdydns.com'
    ]
  },
  QIHOO360: {
    dns: 'https://101.198.198.198/dns-query',
    domains: [
      'qhimg.com',
      'qhimgs0.com',
      'qhimgs1.com',
      'qhimgs2.com',
      'qhimgs3.com',
      'qhimgs4.com',
      'qhimgs5.com',
      'qhimgs6.com',
      'qhres.com',
      'qhres0.com',
      'qhres1.com',
      'qhres2.com',
      'qhres3.com',
      'qhres4.com',
      'qhres5.com',
      'qhres6.com',
      'qhmsg.com',
      'qhstatic.com',
      'qhupdate.com',
      'qihucdn.com',
      '360.com',
      '360.cn',
      '360.net',
      '360safe.com',
      '360tpcdn.com',
      '360os.com',
      '360webcache.com',
      '360kuai.com',
      'so.com',
      'haosou.com',
      'yunpan.cn',
      'yunpan.com',
      'yunpan.com.cn',
      'qh-cdn.com'
    ]
  },
  SYSTEM: {
    dns: 'system',
    domains: [
      '_hotspot_.m2m',
      'hotspot.cslwifi.com',
      'amplifi.lan',
      '*.lan',
      'home.arpa',
      // TailScale Magic DNS
      'ts.net',
      // Aruba Router
      'instant.arubanetworks.com',
      'setmeup.arubanetworks.com',
      // ASUS router
      'router.asus.com',
      'repeater.asus.com',
      'asusrouter.com',
      // NetGear
      'routerlogin.net',
      // Tenda WiFi
      'tendawifi.com',
      // TP-Link Router
      'tplinkwifi.net',
      'tplogin.cn',
      'tplinkap.net',
      'tplinkeap.net',
      'tplinkmodem.net',
      'tplinkplclogin.net',
      'tplinkrepeater.net',
      // Xiaomi Router
      'miwifi.com',
      // ZTE CPE
      'zte.home',
      // Other Router
      'ui.direct',
      'hiwifi.com',
      'huaweimobilewifi.com',
      'my.router',
      'phicomm.me',
      'router.ctc',
      'peiluyou.com',
      'airbox.home',
      'arcor.easybox',
      'aterm.me',
      'bthub.home',
      'bthomehub.home',
      'congstar.box',
      'connect.box',
      'console.gl-inet.com',
      'easy.box',
      'etxr',
      'fritz.box',
      'fritz.nas',
      'fritz.repeater',
      'giga.cube',
      'hi.link',
      'hitronhub.home',
      'homerouter.cpe',
      'myfritz.box',
      'mobile.hotspot',
      'ntt.setup',
      'pi.hole',
      'plex.direct',
      'app.plex.tv',
      'routerlogin.com',
      'samsung.router',
      'speedport.ip',
      'steamloopback.host',
      'web.setup',
      'web.setup.home',
      // AS112
      '10.in-addr.arpa',
      '16.172.in-addr.arpa',
      '17.172.in-addr.arpa',
      '18.172.in-addr.arpa',
      '19.172.in-addr.arpa',
      '20.172.in-addr.arpa',
      '21.172.in-addr.arpa',
      '22.172.in-addr.arpa',
      '23.172.in-addr.arpa',
      '24.172.in-addr.arpa',
      '25.172.in-addr.arpa',
      '26.172.in-addr.arpa',
      '27.172.in-addr.arpa',
      '28.172.in-addr.arpa',
      '29.172.in-addr.arpa',
      '30.172.in-addr.arpa',
      '31.172.in-addr.arpa',
      '168.192.in-addr.arpa',
      '254.169.in-addr.arpa'
    ]
  }
} as const;
