# $ meta_title Sukka's Ruleset - Hong Kong
# $ meta_description This file contains rules for Hong Kong services.

# Futu
DOMAIN-SUFFIX,futu.link
DOMAIN-SUFFIX,futu.com
DOMAIN-SUFFIX,futu.cn
DOMAIN-SUFFIX,futunn.com
DOMAIN-SUFFIX,futu0.com
DOMAIN-SUFFIX,futu1.com
DOMAIN-SUFFIX,futu2.com
DOMAIN-SUFFIX,futu3.com
DOMAIN-SUFFIX,futu4.com
DOMAIN-SUFFIX,futu5.com
DOMAIN-SUFFIX,futu6.com
DOMAIN-SUFFIX,futu7.com
DOMAIN-SUFFIX,futu8.com
DOMAIN-SUFFIX,futu9.com
DOMAIN-SUFFIX,futuau.com
DOMAIN-SUFFIX,futuesop.com
DOMAIN-SUFFIX,futufin.com
DOMAIN-SUFFIX,futuhk.com
DOMAIN-SUFFIX,futuhk2.com
DOMAIN-SUFFIX,futuhkapp.com
DOMAIN-SUFFIX,futuhn.com
DOMAIN-SUFFIX,futuholdings.com
DOMAIN-SUFFIX,futuinc.com
DOMAIN-SUFFIX,futuniuniu.com
DOMAIN-SUFFIX,futubull.cn
DOMAIN-SUFFIX,futuchain.com
DOMAIN-SUFFIX,futustatic.com
DOMAIN-SUFFIX,fututrade.com
DOMAIN-SUFFIX,fututrustee.com
DOMAIN-SUFFIX,cdn.futustatic.com

# Moomoo
DOMAIN-SUFFIX,moomoo.com
DOMAIN-SUFFIX,api.moomoobull.com
DOMAIN-SUFFIX,moomooequity.com
DOMAIN-SUFFIX,moomootrustee.com

# Futu / Moomoo
DOMAIN-SUFFIX,9oju31.launches.appsflyersdk.com
DOMAIN-SUFFIX,sgqt0j.launches.appsflyersdk.com
DOMAIN-SUFFIX,shortconn.im.qcloud.com

# Longbridge
DOMAIN-SUFFIX,api.lbkrs.com
DOMAIN-SUFFIX,api-gl.lbkrs.com
DOMAIN-SUFFIX,longbridge.cloud
DOMAIN-SUFFIX,longbridge.com
DOMAIN-SUFFIX,longbridge.global
DOMAIN-SUFFIX,longbridge.hk
DOMAIN-SUFFIX,longbridge.sg
DOMAIN-SUFFIX,longbridgeapp.com
DOMAIN-SUFFIX,longbridgehk.com

# Tiger Brokers
DOMAIN-SUFFIX,itiger.com
DOMAIN-SUFFIX,tigerbrokers.com
DOMAIN-SUFFIX,tigerbrokers.net
DOMAIN-SUFFIX,tigerbrokers.nz
DOMAIN-SUFFIX,tigerfintech.com
DOMAIN-SUFFIX,laohu8.com
DOMAIN-SUFFIX,tigerbbs.cn
DOMAIN-SUFFIX,tigerbbs.com
DOMAIN-SUFFIX,xiaohu8.com
DOMAIN-SUFFIX,zhijianfengyi.cn
DOMAIN-SUFFIX,zhijianfengyi.com
