import type { DNSMapping } from './direct';

export const GLOBAL: Record<string, DNSMapping> = {
  GOOGLE: {
    hosts: {},
    // This DNS doesn't include in sukka_local_dns_mapping sgmodule
    // TODO: make a smartdns/adguardhome config for proxy servers
    dns: 'https://8.8.4.4/dns-query',
    realip: false,
    ruleset: false,
    domains: [
      'abc.xyz',
      'ampproject.org',
      'android.com',
      'androidify.com',
      'appspot.com',
      'autodraw.com',
      'blogger.com',
      'blogblog.com',
      'blogspot.com',
      'capitalg.com',
      'certificate-transparency.org',
      'chrome.com',
      'chromeexperiments.com',
      'chromestatus.com',
      'chromium.org',
      'circle.ms',
      'cloudfunctions.net',
      'creativelab5.com',
      'debug.com',
      'deepmind.com',
      'dialogflow.com',
      'feedburner.com',
      'forms.gle',
      'firebaseio.com',
      'g.co',
      'gcr.io',
      'getmdl.io',
      'getoutline.org',
      'ggpht.com',
      'glitch.com',
      'gmail.com',
      'gmodules.com',
      'godoc.org',
      'golang.org',
      'goo.gl',
      'googl.com',
      'google.com',
      'google.hk',
      'google.com.hk',
      'google.tw',
      'google.com.tw',
      'google.com.sg',
      'google.jp',
      'google.co.jp',
      'googleapis.com',
      'googleapis.cn',
      'googlesource.com',
      'gstatic.com',
      'gv.com',
      'gvt0.com',
      'gvt1.com',
      'gvt2.com',
      'gvt3.com',
      'gvt5.com',
      'gvt6.com',
      'gvt7.com',
      'gvt9.com',
      'gwtproject.org',
      'itasoftware.com',
      'madewithcode.com',
      'material.io',
      'page.link',
      'polymer-project.org',
      'recaptcha.net',
      'shattered.io',
      'synergyse.com',
      'tensorflow.org',
      'tiltbrush.com',
      'translate.goog',
      'waveprotocol.org',
      'waymo.com',
      'web.dev',
      'webmproject.org',
      'webpkgcache.com',
      'webrtc.org',
      'whatbrowser.org',
      'widevine.com',
      'x.company',
      'xn--ngstr-lra8j.com',
      'youtu.be',
      'youtube.com',
      'yt.be',
      'ytimg.com',
      'telephony.goog',
      '1e100.net',
      'nest.com',
      'googlezip.net',
      'dns.google',
      '$pki.goog', // ocsp.pki.goog and o.pki.goog is available in Mainland China
      //
      'gooogle.com',
      'firebase.com',
      // GAE
      'run.app',
      // TLDs
      'google',
      'goog'
    ]
  },
  CLOUDFLARE: {
    hosts: {},
    // This DNS doesn't include in sukka_local_dns_mapping sgmodule
    // TODO: make a smartdns/adguardhome config for proxy servers
    dns: 'https://1.0.0.1/dns-query',
    realip: false,
    ruleset: false,
    domains: [
      'cloudflare-dns.com',
      'cloudflare.com',
      'cloudflare.dev',
      'cloudflareresolve.com',
      'cloudflarestatus.com',
      'cloudflareaccess.com'
    ]
  },
  WIKIMEDIA: {
    hosts: {},
    dns: 'https://wikimedia-dns.org/dns-query',
    realip: false,
    ruleset: false,
    domains: [
      'mediawiki.org',
      'wikibooks.org',
      'wikidata.org',
      'wikifunctions.org',
      'wikimedia.org',
      'wikimediafoundation.org',
      'wikinews.org',
      'wikipedia.com',
      'wikipedia.org',
      'wikiquote.org',
      'wikisource.org',
      'wikiversity.org',
      'wikivoyage.org',
      'wiktionary.org',
      'wmfusercontent.org',
      'wmflabs.org',
      'w.wiki'
    ]
  }
};
