# $ meta_title Sukka's Ruleset - Hong Kong Broker
# $ meta_description This file contains rules for Hong Kong brokers.

# Futu
DOMAIN-SUFFIX,futuhk.com
DOMAIN-SUFFIX,futu.link
DOMAIN-SUFFIX,futunn.com
DOMAIN-SUFFIX,futuhn.com
DOMAIN-SUFFIX,futu.com
DOMAIN-SUFFIX,futu0.com
DOMAIN-SUFFIX,futu1.com
DOMAIN-SUFFIX,futu2.com
DOMAIN-SUFFIX,futu3.com
DOMAIN-SUFFIX,futu4.com
DOMAIN-SUFFIX,futu5.com
DOMAIN-SUFFIX,futu6.com
DOMAIN-SUFFIX,futu7.com
DOMAIN-SUFFIX,futu8.com
DOMAIN-SUFFIX,futu9.com
DOMAIN-SUFFIX,futuinc.com
DOMAIN-SUFFIX,futuniuniu.com
DOMAIN-SUFFIX,futu.cn
DOMAIN-SUFFIX,futufin.com
DOMAIN-SUFFIX,futuhk2.com
DOMAIN-SUFFIX,futuholdings.com
DOMAIN-SUFFIX,futuesop.com
DOMAIN-SUFFIX,futubull.cn
DOMAIN-SUFFIX,futuchain.com
DOMAIN-SUFFIX,9oju31.launches.appsflyersdk.com
DOMAIN-SUFFIX,shortconn.im.qcloud.com
DOMAIN-SUFFIX,cdn.futustatic.com
DOMAIN-SUFFIX,api.moomoobull.com
DOMAIN-SUFFIX,sgqt0j.launches.appsflyersdk.com

# Long Bridge
DOMAIN-SUFFIX,api.lbkrs.com
DOMAIN-SUFFIX,api-gl.lbkrs.com
