# $ meta_title Sukka's Ruleset - ChatGPT Voice IPs
# $ meta_description This file contains IPs used by ChatGPT Voice.

# >> OpenAI / ChatGPT Voice
# https://openai.com/chatgpt-voice.json
IP-CIDR,4.155.146.196/32,no-resolve
IP-CIDR,20.168.48.117/32,no-resolve
IP-CIDR,40.118.236.137/32,no-resolve
